FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

RUN addgroup -g 1001 -S nodejs
RUN adduser -S finfinity -u 1001
USER finfinity

EXPOSE 3000

CMD ["node", "server.js"]
